export enum HttpErrorString {
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  UNAUTHORIZED = 'UNAUTHORIZED',
  MISSING_RIGHTS = 'MISSING_RIGHTS',
  AMBIGIOUS_REQUEST = 'AMBIGIOUS_REQUEST',
  BAD_REQUEST = 'BAD_REQUEST',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  INVALID_STATE = 'INVALID_STATE',
  INVALID_PARAMETER = 'INVALID_PARAMETER',
}
